#!/bin/sh
version=${1:?"no version number provided"}
set -e -x
dch -m -v "$version" -u low -c doc/changelog
sed -i -r -e "s/(AC_INIT[(]\[nonogram\],) \[[0-9.]+\]/\1 [$version]/" configure.ac
sed -i -r -e "s/<(!ENTITY version) '[0-9.]+'>/<\1 '$version'>/" doc/*.xml
